global:
  scrape_interval: 5s
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - localhost:9093

scrape_configs:
  - job_name: 'weather'
    static_configs:
      - targets: ["localhost:2995"]
